//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 02:28:10 PM CST 
//


package com.navis.argo.webservice.types.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.navis.argo.webservice.types.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.navis.argo.webservice.types.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtendedDetailsType }
     * 
     */
    public ExtendedDetailsType createExtendedDetailsType() {
        return new ExtendedDetailsType();
    }

    /**
     * Create an instance of {@link AddressesType }
     * 
     */
    public AddressesType createAddressesType() {
        return new AddressesType();
    }

    /**
     * Create an instance of {@link PhonesType }
     * 
     */
    public PhonesType createPhonesType() {
        return new PhonesType();
    }

    /**
     * Create an instance of {@link GenericInvokeResponseWsType }
     * 
     */
    public GenericInvokeResponseWsType createGenericInvokeResponseWsType() {
        return new GenericInvokeResponseWsType();
    }

    /**
     * Create an instance of {@link ScopeCoordinateIdsWsType }
     * 
     */
    public ScopeCoordinateIdsWsType createScopeCoordinateIdsWsType() {
        return new ScopeCoordinateIdsWsType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link CountryListType }
     * 
     */
    public CountryListType createCountryListType() {
        return new CountryListType();
    }

    /**
     * Create an instance of {@link QueryResultType }
     * 
     */
    public QueryResultType createQueryResultType() {
        return new QueryResultType();
    }

    /**
     * Create an instance of {@link MessageCollectorType }
     * 
     */
    public MessageCollectorType createMessageCollectorType() {
        return new MessageCollectorType();
    }

    /**
     * Create an instance of {@link Empty }
     * 
     */
    public Empty createEmpty() {
        return new Empty();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link ScopeCoordinates }
     * 
     */
    public ScopeCoordinates createScopeCoordinates() {
        return new ScopeCoordinates();
    }

    /**
     * Create an instance of {@link LanguageListType }
     * 
     */
    public LanguageListType createLanguageListType() {
        return new LanguageListType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link CredentialType }
     * 
     */
    public CredentialType createCredentialType() {
        return new CredentialType();
    }

    /**
     * Create an instance of {@link ExtendedDetailsType.ExtendedDetail }
     * 
     */
    public ExtendedDetailsType.ExtendedDetail createExtendedDetailsTypeExtendedDetail() {
        return new ExtendedDetailsType.ExtendedDetail();
    }

    /**
     * Create an instance of {@link AddressesType.Address }
     * 
     */
    public AddressesType.Address createAddressesTypeAddress() {
        return new AddressesType.Address();
    }

    /**
     * Create an instance of {@link PhonesType.Phone }
     * 
     */
    public PhonesType.Phone createPhonesTypePhone() {
        return new PhonesType.Phone();
    }

}
